"""API del flujo git_flow; cada responsabilidad tiene su módulo propio."""
from .git_process import (
    DEVELOP_BRANCH,
    GH_TIMEOUT_S,
    GIT_TIMEOUT_S,
    GitFlowError,
    PROTECTED_BRANCHES,
    PUSH_TIMEOUT_S,
    _exec,
    _git,
    _git_out,
)
from .git_branches import (
    _branch_exists,
    branch_name,
    branch_status,
    cleanup_conversation_branch,
    delete_local_branch,
    detect_base_branch,
    fetch_origin_safe,
    has_commits,
    is_git_repo,
    sync_base_with_origin,
    unique_branch_name,
    work_base_branch,
    working_tree_clean,
)
from .git_conversations import (
    DIFF_CAP,
    _EXCLUDE_MARK,
    _TOOL_EXCLUDES,
    _autocommit_pending,
    _cap,
    _current_branch,
    _ensure_develop,
    _existing_pr_url,
    branch_diff,
    conversation_diff,
    ensure_local_excludes,
    finalize_conversation_pr,
    open_conversation_branch,
)
from .git_diff import (
    DIFF_MODES,
    FILE_DIFF_CAP,
    UNTRACKED_MAX_LINES,
    _diff_range,
    _merge_base,
    _num,
    _parse_name_status_z,
    _parse_numstat_z,
    _rel_inside,
    _untracked_diff,
    diff_file,
    diff_file_list,
)
from .git_actions import (
    _guard_work_branch,
    _safe_paths,
    commit_paths,
    merge_pr,
    open_pr,
    push_branch,
    restore_paths,
    sync_base,
)
