"""Tipos y constantes compartidas por el modo nocturno."""
from __future__ import annotations

from dataclasses import dataclass
import re
from typing import Any

from pydantic import BaseModel, Field, field_validator


PLAN_TIMEOUT_S = 300.0          # Fase 1: cuánto puede tardar el planificador
EXPERT_TIMEOUT_S = 900.0        # Fase 2: presupuesto del experto por tarea
GATE_TIMEOUT_S = 600.0          # build/test por gate
GIT_TIMEOUT_S = 60.0            # cada comando git
MIN_TASK_WINDOW_S = 300.0       # no arrancar tarea nueva con < 5 min al deadline
DEFAULT_DEADLINE_HOUR = 7       # 7am local si no viene deadline_iso
CBM_INDEX_LIMIT = 5000          # cuántos File nodes pedimos para validar refs
PLAN_PROMPT_FILES_CAP = 400     # cuántos paths indexados ve el LLM planificador

PLAN_DIRNAME = ".relay"
PLAN_FILENAME = "night-plan.md"

COMMIT_TRAILER = "Auto-generated by 4bis.relay night mode ({run_id})"

# Paths que el worker NUNCA debe tocar (gate de ADR-028 punto 5).
FORBIDDEN_PATTERNS = (".env", "secrets", "migrations", "appsettings.production",)

# Firma del bug de restore en frío del SDK .NET 10.0.204: el PRIMER
# `dotnet build` tras ciertas operaciones git tira "Value cannot be
# null. (Parameter 'path1')" desde NuGet.targets; el restore caliente
# (segundo build) anda. NO es un error del código de la tarea —
# reintentamos el build UNA vez si el output matchea esto. Verificado
# 2026-07-10 en CommerceDemo (build 1 falla path1, builds 2-3 pasan).
TRANSIENT_BUILD_SIGNATURES = (
    "Value cannot be null. (Parameter 'path1')",
    "NuGet.targets",
)


# ---------- plan ledger: formato estricto (NIGHT_MODE_SPEC.md) ----------
#
#   - [ ] T-001: Descripción técnica. (Refs: `path/a.cs`, `path/b.py`)
#   - [x] ...  completada (tests exit 0 + commiteada)
#   - [-] ...  descartada (ref inválida, gate roto, sin tiempo) — nota

_TASK_RE = re.compile(
    r"^- \[([ x-])\] (T-\d{3}): (.*?) \(Refs: (.*?)\)(?: — (.*))?\s*$")
_STATE_TO_CHAR = {"pending": " ", "done": "x", "discarded": "-"}
_CHAR_TO_STATE = {v: k for k, v in _STATE_TO_CHAR.items()}


@dataclass
class NightTask:
    id: str                      # "T-001"
    title: str                   # descripción técnica, una frase
    refs: list[str]              # paths relativos al repo
    status: str = "pending"      # pending | done | discarded
    note: str = ""               # razón de descarte / branch / pr


class PlanDraft(BaseModel):
    """Una tarea propuesta por el LLM (pre-validación)."""
    title: str = Field(description="Descripción técnica imperativa, una frase")
    refs: list[str] = Field(description="Paths relativos al repo, de la lista dada")

    @field_validator("refs", mode="before")
    @classmethod
    def _unwrap_minimax_item(cls, v: Any) -> Any:
        """La capa de function-calling de MiniMax M3 mangla arrays de
        strings anidados: el modelo emite `"refs": ["a", "b"]` (visible
        en su thinking) pero los args llegan como `{"item": [...]}` o
        `{"item": "solo-uno"}`. Es del provider, no del modelo — los 4
        retries fallaban idéntico. Aceptar ambas formas. Caso real:
        un run de ejemplo commercedemo 2026-07-10."""
        if isinstance(v, dict) and set(v) == {"item"}:
            v = v["item"]
        if isinstance(v, str):
            v = [v]
        return v


class PlanDrafts(BaseModel):
    tasks: list[PlanDraft] = Field(default_factory=list)


# ---------- Iter 9.7: pregunta interactiva al humano ----------
# El LLM puede decidir, al final de un bloque lógico, si necesita
# input humano antes de seguir (decisiones irreversibles, ambigüedad
# arquitectural, etc.). El modelo BlockDecision es lo que devuelve
# cuando dice "sí, necesito input". Si no necesita, devuelve None.

class BlockQuestionOption(BaseModel):
    key: str = Field(description="Letra o identificador corto único (A, B, C, ...)")
    label: str = Field(description="Texto humano que describe la opción")


class BlockDecision(BaseModel):
    """Pregunta que el LLM genera al final de un bloque.

    `options` es DINÁMICO: el LLM decide cuántas y cuáles son, según
    lo que necesite saber en ese momento. NO es un menú fijo A/B/C/D
    — el LLM es filtro suficiente.
"""
    title: str = Field(description="Título corto del bloque completado")
    prompt: str = Field(description="Pregunta concreta al humano")
    options: list[BlockQuestionOption] = Field(
        description="Opciones que el LLM considera necesarias (≥ 2)",
    )
    default: str = Field(
        description="Key de la opción que se aplica si no hay respuesta"
    )


@dataclass
class TaskResult:
    task_id: str
    status: str                  # done | rolled_back | failed
    branch: str = ""
    pr_url: str = ""
    error: str = ""
    duration_s: float = 0.0
    # Veredicto del verificador (2026-08-27). El nocturno ya corria el
    # runner por etapas —o sea que PAGABA el verificador— y su respuesta
    # moria en un logger.info: no llegaba al TaskResult, ni al reporte de
    # la manana, ni al PR. Un `needs_human` commiteaba igual y en silencio.
    # Los gates (build/test) siguen decidiendo si se commitea; esto es el
    # juicio, y va al lado para que a las 7am sepas de cuales dudar.
    verdict: str = ""
    verdict_feedback: str = ""
